// shared statuses
const NOT_INITIALIZED = 'NOT_INITIALIZED';
const LOADING = 'LOADING';
const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';

// location statuses
const DENIED = 'DENIED';
const GRANTED = 'GRANTED';
const NOT_SUPPORTED = 'NOT_SUPPORTED';

export { NOT_INITIALIZED, LOADING, SUCCESS, ERROR, DENIED, GRANTED, NOT_SUPPORTED };
